phoenix:
  image: birdhouse/pyramid-phoenix
  ports:
    - "9001:9001"
    - "8081:8081"
    - "8443:8443"
  environment:
    - HOSTNAME
  links:
    - mongodb
mongodb:
  image: birdhouse/mongodb
  command: make update-config update-user start
