phoenix:
  image: birdhouse/pyramid-phoenix
  ports:
    - "9001:9001"
    - "8081:8081"
    - "8443:8443"
  environment:
    HOSTNAME: localhost
  links:
    - mongodb
  volumes:
    - /tmp/data:/opt/birdhouse/var/lib
    - /tmp/log:/opt/birdhouse/var/log
  volume_driver: local
mongodb:
  image: mongo:2.6.12
