name: pyramid-phoenix 
channels:
  - defaults
  - birdhouse
dependencies:
  - python=2.7.12 
  - setuptools=27.2.0
  - curl=7.49.0 
  - pyopenssl=16.0.0
  - cryptography=1.5.2
# tests
  - pytest 
#  - pytest-pep8 
  - flake8
# ipython
  - ipython
# sphinx
  - sphinx 
  - sphinx_rtd_theme
# phoenix
  - nginx=1.10.1
  - supervisor=3.3.1
  - gunicorn=19.1.0
  - gevent=1.1.1
  - lxml=3.6.0
  - mako=1.0.5 
  - dateutil=2.4.1 
  - requests=2.10.0 
  - pyyaml=3.11
  - pygments=2.1.3 
  - pytz=2016.4
  - owslib=0.13.0
  - transaction=1.6.0
# celery
  - celery=3.1.19
  - kombu=3.0.32
# mongodb
  - pymongo=3
  - mongodb=2.6.12
# twitcher
  - pywps=3.2.6
# phoenix extensions 
  - python-swiftclient=2.4.0
  - threddsclient=0.3.4       
  - python-ldap=2.4.13
  - funcsigs=1.0.2
  - bird-feeder=0.2.0
  - pip:
      - genshi==0.7
      - sphinx-autoapi==0.4.0
      - pyramid==1.7
      - pyramid-beaker==0.8
      - pyramid-deform==0.2
      - pyramid-chameleon==0.3
      - pyramid-mako==1.0.2
      - pyramid-layout==1.0
      - pyramid-celery==2.0.0
      - pyramid-mailer==0.14.1
      - pyramid-storage==0.1.2
      - pyramid-ldap==0.1
#      - pyramid-twitcher==0.2.0
      - Authomatic==0.1.0.post1
      - python-openid==2.2.5
      - ldappool==1.0
      - deform==2.0a2
      - WebHelpers2==2.0
      - WebHelpers2_grid==0.1
      - repoze.sendmail==4.2
